version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  builder: html

python:
  version: 3.8
  path: .
  pip_install: true
  requirements: docs/requirements.txt
  extra_requirements:
    - docs
      